### ISSUE TITLE
Where's the 2FA token

### ISSUE THREAD

**Issue by abhiram100** [njalooo/ethz-vpn-connect#1]
Hey, thanks for the great tool. Where do I find the soft token that I need to place in `/secrets/ethzvpntoken.secret`?

**Comment by njalooo** [comment]
Hey, that's the One-Time-Password secret that is used to generate OTP tokens. For some Authenticator apps you can export it, otherwise do what i did and go to password.ethz.ch, and click on "MFA Zurücksetzen"/"Reset MFA". It will be the string of characters displayed below the QR code, once you passed email verification.

Alternatively Edit the Scripts line 7, and remove "--token-mode=totp --token-secret=sha1:base32:$TOKEN", as well as removing line 10 and 4. Then you will be prompted for your OTP token each time you connect.

Let me know if that answered your Question.
